### ISSUE TITLE
Fazer a implementação do Storage

### ISSUE THREAD

**Issue by jacksongarcia** [stone-payments/pos-mamba-browser#10]
O mambabrowser não tem suporte a local storage, isso faz que o parceiro não consiga usar esse módulo da SDK

**Comment by kaisermann** [comment]
A gente já faz um fake "localStorage" no simulador, caso não exista 'window.localStorage' (o que o mambabrowser pode até ter). O único problema é que não é algo persistente

**Comment by luckvargas** [comment]
Done!

**Comment by kaisermann** [comment]
Isso resolve, mas pensei aqui agora: se o cara tenta usar o `localStorage` direto, vai conseguir e vai ficar confuso quando não rolar no POS 🤔

Lembrei aqui que se tiver a `window.$Storage` de verdade, o simulador usa ela, então talvez valha a pena botar ele mesmo 🤔

@luckvargas @jacksongarcia
